name: doctor_appointment_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Updated packages
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.0.9
  lottie: ^3.1.2
  dio: ^5.4.2+1
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.0.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true

  assets:
    - assets/
